<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Chi-square analysis | Data analysis for Newquay University Centre</title>
  <meta name="description" content="A work in progress" />
  <meta name="generator" content="bookdown 0.39 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Chi-square analysis | Data analysis for Newquay University Centre" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="https://newquay-university-centre.github.io/r4nqy//images/logo/newquay_uc.png" />
  <meta property="og:description" content="A work in progress" />
  <meta name="github-repo" content="Newquay-University-Centre/r4nqy" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Chi-square analysis | Data analysis for Newquay University Centre" />
  
  <meta name="twitter:description" content="A work in progress" />
  <meta name="twitter:image" content="https://newquay-university-centre.github.io/r4nqy//images/logo/newquay_uc.png" />

<meta name="author" content="Michael Hunt" />


<meta name="date" content="2024-05-31" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="plot-with-ggplot.html"/>
<link rel="next" href="fishers-exact-test.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #204a87; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #8f5902; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #204a87; font-weight: bold; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #ce5c00; font-weight: bold; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Newquay University Centre</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#usage"><i class="fa fa-check"></i><b>0.1</b> Usage</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#render-book"><i class="fa fa-check"></i><b>0.2</b> Render book</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#preview-book"><i class="fa fa-check"></i><b>0.3</b> Preview book</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="plot-with-ggplot.html"><a href="plot-with-ggplot.html"><i class="fa fa-check"></i><b>1</b> Plot your data</a>
<ul>
<li class="chapter" data-level="1.1" data-path="plot-with-ggplot.html"><a href="plot-with-ggplot.html#load-packages"><i class="fa fa-check"></i><b>1.1</b> Load packages</a></li>
<li class="chapter" data-level="1.2" data-path="plot-with-ggplot.html"><a href="plot-with-ggplot.html#get-the-template-script"><i class="fa fa-check"></i><b>1.2</b> Get the template script</a></li>
<li class="chapter" data-level="1.3" data-path="plot-with-ggplot.html"><a href="plot-with-ggplot.html#load-the-palmer-penguin-data"><i class="fa fa-check"></i><b>1.3</b> Load the Palmer penguin data</a></li>
<li class="chapter" data-level="1.4" data-path="plot-with-ggplot.html"><a href="plot-with-ggplot.html#summary-stats-on-all-the-numeric-columns"><i class="fa fa-check"></i><b>1.4</b> Summary stats on all the numeric columns</a></li>
<li class="chapter" data-level="1.5" data-path="plot-with-ggplot.html"><a href="plot-with-ggplot.html#remove-the-rows-with-nas"><i class="fa fa-check"></i><b>1.5</b> Remove the rows with NAs</a></li>
<li class="chapter" data-level="1.6" data-path="plot-with-ggplot.html"><a href="plot-with-ggplot.html#how-many-observations-are-there-for-each-species"><i class="fa fa-check"></i><b>1.6</b> How many observations are there for each species?</a></li>
<li class="chapter" data-level="1.7" data-path="plot-with-ggplot.html"><a href="plot-with-ggplot.html#mean-value-for-each-numerical-variable-for-each-species"><i class="fa fa-check"></i><b>1.7</b> Mean value for each numerical variable, for each species</a></li>
<li class="chapter" data-level="1.8" data-path="plot-with-ggplot.html"><a href="plot-with-ggplot.html#scatter-plots"><i class="fa fa-check"></i><b>1.8</b> Scatter plots</a></li>
<li class="chapter" data-level="1.9" data-path="plot-with-ggplot.html"><a href="plot-with-ggplot.html#repeat-for-bill-length-and-flipper-length"><i class="fa fa-check"></i><b>1.9</b> Repeat for bill length and flipper length</a></li>
<li class="chapter" data-level="1.10" data-path="plot-with-ggplot.html"><a href="plot-with-ggplot.html#add-yet-more-informtion-to-the-plot"><i class="fa fa-check"></i><b>1.10</b> Add yet more informtion to the plot</a></li>
<li class="chapter" data-level="1.11" data-path="plot-with-ggplot.html"><a href="plot-with-ggplot.html#distribution-of-penguin-flipper-lengths"><i class="fa fa-check"></i><b>1.11</b> Distribution of penguin flipper lengths</a>
<ul>
<li class="chapter" data-level="1.11.1" data-path="plot-with-ggplot.html"><a href="plot-with-ggplot.html#histogram"><i class="fa fa-check"></i><b>1.11.1</b> Histogram</a></li>
<li class="chapter" data-level="1.11.2" data-path="plot-with-ggplot.html"><a href="plot-with-ggplot.html#density-plot"><i class="fa fa-check"></i><b>1.11.2</b> Density plot</a></li>
<li class="chapter" data-level="1.11.3" data-path="plot-with-ggplot.html"><a href="plot-with-ggplot.html#box-plots"><i class="fa fa-check"></i><b>1.11.3</b> Box plots</a></li>
<li class="chapter" data-level="1.11.4" data-path="plot-with-ggplot.html"><a href="plot-with-ggplot.html#violin-plot-using-geom_violin"><i class="fa fa-check"></i><b>1.11.4</b> Violin Plot using <code>geom_violin()</code></a></li>
<li class="chapter" data-level="1.11.5" data-path="plot-with-ggplot.html"><a href="plot-with-ggplot.html#ridge-plot"><i class="fa fa-check"></i><b>1.11.5</b> Ridge plot</a></li>
</ul></li>
<li class="chapter" data-level="1.12" data-path="plot-with-ggplot.html"><a href="plot-with-ggplot.html#bar-chart-with-error-bar"><i class="fa fa-check"></i><b>1.12</b> Bar chart with error bar</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="chi-square.html"><a href="chi-square.html"><i class="fa fa-check"></i><b>2</b> Chi-square analysis</a>
<ul>
<li class="chapter" data-level="2.1" data-path="chi-square.html"><a href="chi-square.html#chi-square-goodness-of-fit-test"><i class="fa fa-check"></i><b>2.1</b> Chi-square goodness of fit test</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="chi-square.html"><a href="chi-square.html#example"><i class="fa fa-check"></i><b>2.1.1</b> Example</a></li>
<li class="chapter" data-level="2.1.2" data-path="chi-square.html"><a href="chi-square.html#doing-the-chi-square-test-in-r"><i class="fa fa-check"></i><b>2.1.2</b> Doing the chi-square test in R</a></li>
<li class="chapter" data-level="2.1.3" data-path="chi-square.html"><a href="chi-square.html#reporting-the-result-in-english"><i class="fa fa-check"></i><b>2.1.3</b> Reporting the result in English</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="chi-square.html"><a href="chi-square.html#exercise-1."><i class="fa fa-check"></i><b>2.2</b> Exercise 1.</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="chi-square.html"><a href="chi-square.html#solution.-1"><i class="fa fa-check"></i><b>2.2.1</b> Solution. 1</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="chi-square.html"><a href="chi-square.html#way-chi-square-analysis-test-of-independence"><i class="fa fa-check"></i><b>2.3</b> 2-way chi square analysis: test of independence</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="chi-square.html"><a href="chi-square.html#hypotheses"><i class="fa fa-check"></i><b>2.3.1</b> Hypotheses</a></li>
<li class="chapter" data-level="2.3.2" data-path="chi-square.html"><a href="chi-square.html#summarise-the-data."><i class="fa fa-check"></i><b>2.3.2</b> Summarise the data.</a></li>
<li class="chapter" data-level="2.3.3" data-path="chi-square.html"><a href="chi-square.html#plot-the-data."><i class="fa fa-check"></i><b>2.3.3</b> Plot the data.</a></li>
<li class="chapter" data-level="2.3.4" data-path="chi-square.html"><a href="chi-square.html#interpret-the-graph-before-we-do-any-stats"><i class="fa fa-check"></i><b>2.3.4</b> Interpret the graph before we do any ‘stats’</a></li>
<li class="chapter" data-level="2.3.5" data-path="chi-square.html"><a href="chi-square.html#the-chi-square-test"><i class="fa fa-check"></i><b>2.3.5</b> The Chi-square test</a></li>
<li class="chapter" data-level="2.3.6" data-path="chi-square.html"><a href="chi-square.html#yates-continuity-correction"><i class="fa fa-check"></i><b>2.3.6</b> Yates continuity correction</a></li>
<li class="chapter" data-level="2.3.7" data-path="chi-square.html"><a href="chi-square.html#conclusion"><i class="fa fa-check"></i><b>2.3.7</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="chi-square.html"><a href="chi-square.html#the-chi-square-test-explained-advanced"><i class="fa fa-check"></i><b>2.4</b> The Chi-Square Test explained (advanced)</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="chi-square.html"><a href="chi-square.html#why-does-the-test-statistic-have-this-distribution"><i class="fa fa-check"></i><b>2.4.1</b> Why does the test statistic have this distribution?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="fishers-exact-test.html"><a href="fishers-exact-test.html"><i class="fa fa-check"></i><b>3</b> Fisher’s exact test</a>
<ul>
<li class="chapter" data-level="3.1" data-path="fishers-exact-test.html"><a href="fishers-exact-test.html#the-hypergeometric-function"><i class="fa fa-check"></i><b>3.1</b> The Hypergeometric Function</a></li>
<li class="chapter" data-level="3.2" data-path="fishers-exact-test.html"><a href="fishers-exact-test.html#hypergeometric-distribution-in-r"><i class="fa fa-check"></i><b>3.2</b> Hypergeometric Distribution in R</a></li>
<li class="chapter" data-level="3.3" data-path="fishers-exact-test.html"><a href="fishers-exact-test.html#back-to-fishers-exact-test"><i class="fa fa-check"></i><b>3.3</b> Back to Fisher’s Exact Test</a></li>
<li class="chapter" data-level="3.4" data-path="fishers-exact-test.html"><a href="fishers-exact-test.html#example-1"><i class="fa fa-check"></i><b>3.4</b> Example</a></li>
<li class="chapter" data-level="3.5" data-path="fishers-exact-test.html"><a href="fishers-exact-test.html#fishers-exact-test-in-r"><i class="fa fa-check"></i><b>3.5</b> Fisher’s Exact Test in R</a></li>
<li class="chapter" data-level="3.6" data-path="fishers-exact-test.html"><a href="fishers-exact-test.html#what-if-we-just-use-a-chi-square-test"><i class="fa fa-check"></i><b>3.6</b> What if we just use a chi-square test?</a></li>
<li class="chapter" data-level="3.7" data-path="fishers-exact-test.html"><a href="fishers-exact-test.html#why-not-always-use-fishers-exact-test-instead-of-a-chi-square-test"><i class="fa fa-check"></i><b>3.7</b> Why not always use Fisher’s Exact Test instead of a chi-square test?</a></li>
<li class="chapter" data-level="3.8" data-path="fishers-exact-test.html"><a href="fishers-exact-test.html#another-cautionary-note"><i class="fa fa-check"></i><b>3.8</b> Another Cautionary Note</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="difference.html"><a href="difference.html"><i class="fa fa-check"></i><b>4</b> t-test for difference</a>
<ul>
<li class="chapter" data-level="4.1" data-path="difference.html"><a href="difference.html#preliminaries"><i class="fa fa-check"></i><b>4.1</b> Preliminaries</a></li>
<li class="chapter" data-level="4.2" data-path="difference.html"><a href="difference.html#motivation-and-example"><i class="fa fa-check"></i><b>4.2</b> Motivation and example</a></li>
<li class="chapter" data-level="4.3" data-path="difference.html"><a href="difference.html#the-two-sample-t-test"><i class="fa fa-check"></i><b>4.3</b> The two-sample <em>t</em>-test</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="difference.html"><a href="difference.html#pros-of-the-t-test"><i class="fa fa-check"></i><b>4.3.1</b> Pros of the <em>t</em>-test</a></li>
<li class="chapter" data-level="4.3.2" data-path="difference.html"><a href="difference.html#cons-of-the-t-test"><i class="fa fa-check"></i><b>4.3.2</b> Cons of the <em>t</em>-test</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="difference.html"><a href="difference.html#the-workflow"><i class="fa fa-check"></i><b>4.4</b> The workflow</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="difference.html"><a href="difference.html#open-your-project"><i class="fa fa-check"></i><b>4.4.1</b> Open your project</a></li>
<li class="chapter" data-level="4.4.2" data-path="difference.html"><a href="difference.html#create-a-new-script"><i class="fa fa-check"></i><b>4.4.2</b> Create a new script</a></li>
<li class="chapter" data-level="4.4.3" data-path="difference.html"><a href="difference.html#load-packages-1"><i class="fa fa-check"></i><b>4.4.3</b> Load packages</a></li>
<li class="chapter" data-level="4.4.4" data-path="difference.html"><a href="difference.html#read-in-and-inspect-the-data"><i class="fa fa-check"></i><b>4.4.4</b> Read in and inspect the data</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="difference.html"><a href="difference.html#step-one-summarise-the-data"><i class="fa fa-check"></i><b>4.5</b> Step One: Summarise the data</a></li>
<li class="chapter" data-level="4.6" data-path="difference.html"><a href="difference.html#step-two-plot-the-data"><i class="fa fa-check"></i><b>4.6</b> Step Two: Plot the data</a></li>
<li class="chapter" data-level="4.7" data-path="difference.html"><a href="difference.html#step-three-carry-out-statistical-analysis"><i class="fa fa-check"></i><b>4.7</b> Step Three: Carry out statistical analysis</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="difference.html"><a href="difference.html#are-the-data-normally-distributed"><i class="fa fa-check"></i><b>4.7.1</b> Are the data normally distributed?</a></li>
<li class="chapter" data-level="4.7.2" data-path="difference.html"><a href="difference.html#normality-test---analytical-method"><i class="fa fa-check"></i><b>4.7.2</b> Normality test - analytical method</a></li>
<li class="chapter" data-level="4.7.3" data-path="difference.html"><a href="difference.html#graphical-methods---the-quantile-quantile-or-qq-plot."><i class="fa fa-check"></i><b>4.7.3</b> Graphical methods - the quantile-quantile or QQ plot.</a></li>
<li class="chapter" data-level="4.7.4" data-path="difference.html"><a href="difference.html#the-thinking-about-the-data-normality-test"><i class="fa fa-check"></i><b>4.7.4</b> The ‘thinking about the data’ normality test</a></li>
<li class="chapter" data-level="4.7.5" data-path="difference.html"><a href="difference.html#now-for-the-actual-two-sample-t-test"><i class="fa fa-check"></i><b>4.7.5</b> Now for the actual two-sample <em>t</em>-test</a></li>
<li class="chapter" data-level="4.7.6" data-path="difference.html"><a href="difference.html#interpret-the-output-of-the-t-test."><i class="fa fa-check"></i><b>4.7.6</b> Interpret the output of the <em>t</em>-test.</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="difference.html"><a href="difference.html#the-complete-script"><i class="fa fa-check"></i><b>4.8</b> The complete script</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html"><i class="fa fa-check"></i><b>5</b> Paired tests for difference</a>
<ul>
<li class="chapter" data-level="5.1" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html#which-test-paired-t-test-or-wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>5.1</b> Which test: paired t-test or Wilcoxon signed rank test?</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html#the-paired-t-test"><i class="fa fa-check"></i><b>5.1.1</b> The paired t-test</a></li>
<li class="chapter" data-level="5.1.2" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html#the-wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>5.1.2</b> The Wilcoxon Signed Rank test</a></li>
<li class="chapter" data-level="5.1.3" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html#null-hypotheses"><i class="fa fa-check"></i><b>5.1.3</b> Null Hypotheses</a></li>
<li class="chapter" data-level="5.1.4" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html#test-output"><i class="fa fa-check"></i><b>5.1.4</b> Test output</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html#example-2"><i class="fa fa-check"></i><b>5.2</b> Example</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html#load-packages-2"><i class="fa fa-check"></i><b>5.2.1</b> Load packages</a></li>
<li class="chapter" data-level="5.2.2" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html#load-data"><i class="fa fa-check"></i><b>5.2.2</b> Load data</a></li>
<li class="chapter" data-level="5.2.3" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html#plot-the-data"><i class="fa fa-check"></i><b>5.2.3</b> Plot the data</a></li>
<li class="chapter" data-level="5.2.4" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html#tidy-the-data"><i class="fa fa-check"></i><b>5.2.4</b> Tidy the data</a></li>
<li class="chapter" data-level="5.2.5" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html#check-for-normality-of-differences"><i class="fa fa-check"></i><b>5.2.5</b> Check for normality of differences</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html#the-non-parametric-alternative-the-wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>5.3</b> The non-parametric alternative: The Wilcoxon signed rank test</a></li>
<li class="chapter" data-level="5.4" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html#relation-to-one-sample-paired-test"><i class="fa fa-check"></i><b>5.4</b> Relation to one-sample paired test</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="anova-two-way.html"><a href="anova-two-way.html"><i class="fa fa-check"></i><b>6</b> ANOVA: Two-way factorial experiments and model simplification</a>
<ul>
<li class="chapter" data-level="6.1" data-path="anova-two-way.html"><a href="anova-two-way.html#factorial-experiments-and-model-simplification"><i class="fa fa-check"></i><b>6.1</b> Factorial experiments and model simplification</a></li>
<li class="chapter" data-level="6.2" data-path="anova-two-way.html"><a href="anova-two-way.html#files-needed"><i class="fa fa-check"></i><b>6.2</b> Files needed</a></li>
<li class="chapter" data-level="6.3" data-path="anova-two-way.html"><a href="anova-two-way.html#open-your-project-1"><i class="fa fa-check"></i><b>6.3</b> Open your Project</a></li>
<li class="chapter" data-level="6.4" data-path="anova-two-way.html"><a href="anova-two-way.html#load-packages-3"><i class="fa fa-check"></i><b>6.4</b> Load packages</a></li>
<li class="chapter" data-level="6.5" data-path="anova-two-way.html"><a href="anova-two-way.html#read-in-the-data"><i class="fa fa-check"></i><b>6.5</b> Read in the data</a></li>
<li class="chapter" data-level="6.6" data-path="anova-two-way.html"><a href="anova-two-way.html#make-r-recognise-the-categorical-variables-as-factors-and-order-the-levels."><i class="fa fa-check"></i><b>6.6</b> Make R recognise the categorical variables as factors, and order the levels.</a></li>
<li class="chapter" data-level="6.7" data-path="anova-two-way.html"><a href="anova-two-way.html#summarise-the-data"><i class="fa fa-check"></i><b>6.7</b> Summarise the data</a></li>
<li class="chapter" data-level="6.8" data-path="anova-two-way.html"><a href="anova-two-way.html#plot-the-data-1"><i class="fa fa-check"></i><b>6.8</b> Plot the data</a>
<ul>
<li class="chapter" data-level="6.8.1" data-path="anova-two-way.html"><a href="anova-two-way.html#questions"><i class="fa fa-check"></i><b>6.8.1</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="anova-two-way.html"><a href="anova-two-way.html#anova"><i class="fa fa-check"></i><b>6.9</b> ANOVA</a>
<ul>
<li class="chapter" data-level="6.9.1" data-path="anova-two-way.html"><a href="anova-two-way.html#construct-the-model"><i class="fa fa-check"></i><b>6.9.1</b> Construct the model</a></li>
<li class="chapter" data-level="6.9.2" data-path="anova-two-way.html"><a href="anova-two-way.html#do-we-reject-the-null-hypothesis"><i class="fa fa-check"></i><b>6.9.2</b> Do we reject the null hypothesis?</a></li>
</ul></li>
<li class="chapter" data-level="6.10" data-path="anova-two-way.html"><a href="anova-two-way.html#model-simplification"><i class="fa fa-check"></i><b>6.10</b> Model Simplification</a>
<ul>
<li class="chapter" data-level="6.10.1" data-path="anova-two-way.html"><a href="anova-two-way.html#check-the-validity-of-the-linear-model"><i class="fa fa-check"></i><b>6.10.1</b> Check the validity of the linear model</a></li>
</ul></li>
<li class="chapter" data-level="6.11" data-path="anova-two-way.html"><a href="anova-two-way.html#reporting-the-results"><i class="fa fa-check"></i><b>6.11</b> Reporting the results</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="anova-one-way.html"><a href="anova-one-way.html"><i class="fa fa-check"></i><b>7</b> One-way ANOVA</a>
<ul>
<li class="chapter" data-level="7.1" data-path="anova-one-way.html"><a href="anova-one-way.html#load-packages-4"><i class="fa fa-check"></i><b>7.1</b> Load packages</a></li>
<li class="chapter" data-level="7.2" data-path="anova-one-way.html"><a href="anova-one-way.html#remove-observations-with-missing-values"><i class="fa fa-check"></i><b>7.2</b> Remove observations with missing values</a></li>
<li class="chapter" data-level="7.3" data-path="anova-one-way.html"><a href="anova-one-way.html#summary---group-by-species-and-sex"><i class="fa fa-check"></i><b>7.3</b> Summary - group by species and sex</a></li>
<li class="chapter" data-level="7.4" data-path="anova-one-way.html"><a href="anova-one-way.html#plot-the-data-2"><i class="fa fa-check"></i><b>7.4</b> Plot the data</a></li>
<li class="chapter" data-level="7.5" data-path="anova-one-way.html"><a href="anova-one-way.html#one-way-anova"><i class="fa fa-check"></i><b>7.5</b> One-way ANOVA</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="anova-one-way.html"><a href="anova-one-way.html#null-hypothesis"><i class="fa fa-check"></i><b>7.5.1</b> Null hypothesis</a></li>
<li class="chapter" data-level="7.5.2" data-path="anova-one-way.html"><a href="anova-one-way.html#the-actual-anova"><i class="fa fa-check"></i><b>7.5.2</b> The actual ANOVA</a></li>
<li class="chapter" data-level="7.5.3" data-path="anova-one-way.html"><a href="anova-one-way.html#construct-the-model-1"><i class="fa fa-check"></i><b>7.5.3</b> Construct the model</a></li>
<li class="chapter" data-level="7.5.4" data-path="anova-one-way.html"><a href="anova-one-way.html#is-the-model-valid"><i class="fa fa-check"></i><b>7.5.4</b> Is the model valid?</a></li>
<li class="chapter" data-level="7.5.5" data-path="anova-one-way.html"><a href="anova-one-way.html#the-overall-picture"><i class="fa fa-check"></i><b>7.5.5</b> The overall picture</a></li>
<li class="chapter" data-level="7.5.6" data-path="anova-one-way.html"><a href="anova-one-way.html#the-detailed-picture"><i class="fa fa-check"></i><b>7.5.6</b> The detailed picture</a></li>
<li class="chapter" data-level="7.5.7" data-path="anova-one-way.html"><a href="anova-one-way.html#post-hoc-tsts."><i class="fa fa-check"></i><b>7.5.7</b> Post hoc tsts.</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="anova-one-way.html"><a href="anova-one-way.html#reporting-the-result."><i class="fa fa-check"></i><b>7.6</b> Reporting the Result.</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="correlation.html"><a href="correlation.html"><i class="fa fa-check"></i><b>8</b> Correlation</a>
<ul>
<li class="chapter" data-level="8.1" data-path="correlation.html"><a href="correlation.html#the-correlation-coefficient"><i class="fa fa-check"></i><b>8.1</b> The correlation coefficient</a></li>
<li class="chapter" data-level="8.2" data-path="correlation.html"><a href="correlation.html#different-values-of-r."><i class="fa fa-check"></i><b>8.2</b> Different values of <em>r</em>.</a></li>
<li class="chapter" data-level="8.3" data-path="correlation.html"><a href="correlation.html#using-r-to-find-the-correlation-coefficient."><i class="fa fa-check"></i><b>8.3</b> Using R to find the correlation coefficient.</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="correlation.html"><a href="correlation.html#correlations-for-real-data"><i class="fa fa-check"></i><b>8.3.1</b> Correlations for real data</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="correlation.html"><a href="correlation.html#the-correlation-coefficient-measures-the-degree-of-linear-association."><i class="fa fa-check"></i><b>8.4</b> The correlation coefficient measures the degree of linear association.</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="correlation.html"><a href="correlation.html#when-is-it-appropriate-to-calculate-a-correlation-coefficient"><i class="fa fa-check"></i><b>8.4.1</b> When is it appropriate to calculate a correlation coefficient?</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="correlation.html"><a href="correlation.html#association-is-not-causation"><i class="fa fa-check"></i><b>8.5</b> Association is not causation</a></li>
<li class="chapter" data-level="8.6" data-path="correlation.html"><a href="correlation.html#examples"><i class="fa fa-check"></i><b>8.6</b> Examples</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="correlation.html"><a href="correlation.html#lichen-abundance"><i class="fa fa-check"></i><b>8.6.1</b> Lichen abundance</a></li>
<li class="chapter" data-level="8.6.2" data-path="correlation.html"><a href="correlation.html#soil-bacteria"><i class="fa fa-check"></i><b>8.6.2</b> Soil bacteria</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="correlation.html"><a href="correlation.html#exercises"><i class="fa fa-check"></i><b>8.7</b> Exercises</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="correlation.html"><a href="correlation.html#exercise-1"><i class="fa fa-check"></i><b>8.7.1</b> Exercise 1</a></li>
<li class="chapter" data-level="8.7.2" data-path="correlation.html"><a href="correlation.html#exercise-2"><i class="fa fa-check"></i><b>8.7.2</b> Exercise 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="simple-linear-regression-linear-regression.html"><a href="simple-linear-regression-linear-regression.html"><i class="fa fa-check"></i><b>9</b> Simple linear regression {#linear regression}</a>
<ul>
<li class="chapter" data-level="9.1" data-path="simple-linear-regression-linear-regression.html"><a href="simple-linear-regression-linear-regression.html#simple-linear-regression"><i class="fa fa-check"></i><b>9.1</b> Simple Linear Regression</a></li>
<li class="chapter" data-level="9.2" data-path="simple-linear-regression-linear-regression.html"><a href="simple-linear-regression-linear-regression.html#load-packages-5"><i class="fa fa-check"></i><b>9.2</b> Load packages</a></li>
<li class="chapter" data-level="9.3" data-path="simple-linear-regression-linear-regression.html"><a href="simple-linear-regression-linear-regression.html#get-the-data"><i class="fa fa-check"></i><b>9.3</b> Get the data</a></li>
<li class="chapter" data-level="9.4" data-path="simple-linear-regression-linear-regression.html"><a href="simple-linear-regression-linear-regression.html#plot-the-data-3"><i class="fa fa-check"></i><b>9.4</b> Plot the data</a></li>
<li class="chapter" data-level="9.5" data-path="simple-linear-regression-linear-regression.html"><a href="simple-linear-regression-linear-regression.html#make-a-simple-model-using-linear-regression"><i class="fa fa-check"></i><b>9.5</b> Make a simple model using linear regression</a></li>
<li class="chapter" data-level="9.6" data-path="simple-linear-regression-linear-regression.html"><a href="simple-linear-regression-linear-regression.html#check-assumptions"><i class="fa fa-check"></i><b>9.6</b> Check assumptions</a></li>
<li class="chapter" data-level="9.7" data-path="simple-linear-regression-linear-regression.html"><a href="simple-linear-regression-linear-regression.html#interpretation-of-the-model"><i class="fa fa-check"></i><b>9.7</b> Interpretation of the model</a></li>
<li class="chapter" data-level="9.8" data-path="simple-linear-regression-linear-regression.html"><a href="simple-linear-regression-linear-regression.html#back-to-the-figure"><i class="fa fa-check"></i><b>9.8</b> Back to the figure</a></li>
<li class="chapter" data-level="9.9" data-path="simple-linear-regression-linear-regression.html"><a href="simple-linear-regression-linear-regression.html#conclusion-1"><i class="fa fa-check"></i><b>9.9</b> Conclusion</a></li>
<li class="chapter" data-level="9.10" data-path="simple-linear-regression-linear-regression.html"><a href="simple-linear-regression-linear-regression.html#sample-script"><i class="fa fa-check"></i><b>9.10</b> Sample script</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="a-primer-in-statistics.html"><a href="a-primer-in-statistics.html"><i class="fa fa-check"></i><b>A</b> A primer in statistics</a>
<ul>
<li class="chapter" data-level="A.1" data-path="a-primer-in-statistics.html"><a href="a-primer-in-statistics.html#populations-and-samples"><i class="fa fa-check"></i><b>A.1</b> Populations and samples</a></li>
<li class="chapter" data-level="A.2" data-path="a-primer-in-statistics.html"><a href="a-primer-in-statistics.html#three-types-of-variability-of-the-sample-of-the-population-and-of-the-estimate."><i class="fa fa-check"></i><b>A.2</b> Three types of variability: of the sample, of the population and of the estimate.</a>
<ul>
<li class="chapter" data-level="A.2.1" data-path="a-primer-in-statistics.html"><a href="a-primer-in-statistics.html#variability-of-the-sample"><i class="fa fa-check"></i><b>A.2.1</b> Variability of the sample</a></li>
<li class="chapter" data-level="A.2.2" data-path="a-primer-in-statistics.html"><a href="a-primer-in-statistics.html#variability-of-the-population"><i class="fa fa-check"></i><b>A.2.2</b> Variability of the population</a></li>
<li class="chapter" data-level="A.2.3" data-path="a-primer-in-statistics.html"><a href="a-primer-in-statistics.html#variability-of-the-estimate"><i class="fa fa-check"></i><b>A.2.3</b> Variability of the estimate</a></li>
</ul></li>
<li class="chapter" data-level="A.3" data-path="a-primer-in-statistics.html"><a href="a-primer-in-statistics.html#confidence-intervals-a-way-of-precisely-representing-uncertainty"><i class="fa fa-check"></i><b>A.3</b> Confidence intervals: a way of precisely representing uncertainty</a></li>
<li class="chapter" data-level="A.4" data-path="a-primer-in-statistics.html"><a href="a-primer-in-statistics.html#the-t-distribution"><i class="fa fa-check"></i><b>A.4</b> The <span class="math inline">\(t\)</span>-distribution</a></li>
<li class="chapter" data-level="A.5" data-path="a-primer-in-statistics.html"><a href="a-primer-in-statistics.html#hypothesis-testing"><i class="fa fa-check"></i><b>A.5</b> Hypothesis testing</a>
<ul>
<li class="chapter" data-level="A.5.1" data-path="a-primer-in-statistics.html"><a href="a-primer-in-statistics.html#general-procedure-for-a-hypothesis-test"><i class="fa fa-check"></i><b>A.5.1</b> General procedure for a hypothesis test</a></li>
<li class="chapter" data-level="A.5.2" data-path="a-primer-in-statistics.html"><a href="a-primer-in-statistics.html#comparing-one-mean-with-a-threshold---one-sample-t-test"><i class="fa fa-check"></i><b>A.5.2</b> Comparing one mean with a threshold - one sample <em>t</em>-test</a></li>
<li class="chapter" data-level="A.5.3" data-path="a-primer-in-statistics.html"><a href="a-primer-in-statistics.html#comparing-two-means---two-sample-test"><i class="fa fa-check"></i><b>A.5.3</b> Comparing two means - two-sample test</a></li>
<li class="chapter" data-level="A.5.4" data-path="a-primer-in-statistics.html"><a href="a-primer-in-statistics.html#alternatives-to-the-t-test"><i class="fa fa-check"></i><b>A.5.4</b> Alternatives to the <em>t</em>-test</a></li>
</ul></li>
<li class="chapter" data-level="A.6" data-path="a-primer-in-statistics.html"><a href="a-primer-in-statistics.html#size-effects-vs-hypothesis-testing."><i class="fa fa-check"></i><b>A.6</b> Size effects vs hypothesis testing.</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data analysis for Newquay University Centre</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="chi-square" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Chapter 2</span> Chi-square analysis<a href="chi-square.html#chi-square" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="chi-square-goodness-of-fit-test" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Chi-square goodness of fit test<a href="chi-square.html#chi-square-goodness-of-fit-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A chi-square analysis is used when our data are in the form of raw counts for two or more categorical groups eg pea plants with either yellow peas or green peas, survival rate of mice if they took drug A or took drug B, etc. Each independent observation must definitely belong to either one group or the other, and there are no replicates. That is, for each category we just have one count.</p>
<p>What we do is compare the counts we got to some <em>expected</em> value according either to chance or to some prior theory.</p>
<p>For example:</p>
<ul>
<li><p>If we were tossing a fair coin 1000 times we would <em>expect</em> 500 heads and 500 tails, ie heads and tails in the proportion 1:1. In reality, if the coin were fair, we would probably get roughly the same number of heads and tails, but probably not exactly 500 of each. How far from 50:50 would the proportion of heads and tails have to be before we would be justified in rejecting the idea that the coin is fair?</p></li>
<li><p>If we threw a fair dice a large number of times we would <em>expect</em> each possible score, from 1 to 6, to occur the same number of times. ie each score would occur 1/6th of the time. In reality we would probably get each score <em>roughly</em> 1/6 of the time, but not exactly 1/6. How far from the expected proportions could the numbers of each score get before we would be justified in thinking that the dice was not fair?</p></li>
<li><p>If the basic idea of Mendelian inheritance with independent assortment involving a single gene is correct, then we would expect that if we crossed a large number of pea plants that were heterozygous for yellow and green pea colour, with yellow being dominant, then the offspring would have yellow:green peas in the ratio 3:1 (plants with genotypes YY, Yy, yY would all have yellow seeds and only those with yy would have green seeds). In practice, if the inheritance <em>were</em> according to the simplest type of Mendelian inheritance (ie involving just one gene, amongst other things) we would probably get yellow:green offspring in a ratio that was approximately but not exactly 3:1. How far from 3:1 would the ratio need to be before we would justified in claiming that the outcome was inconsistent with the Mendelian prediction?</p></li>
</ul>
<p>In a chi-square ‘goodness of fit’ test, we are testing data where we have a number of counts for each of two or more possible outcomes of some procedure (heads/tails, dice scores etc). We have an idea of how these counts should be distributed under some null hypothesis (the coin is fair, the dice is fair, genetic inheritance works in this or that way etc). The chi-square goodness of fit test tests how likely it is we would have got the counts we actually got if that null hypothesis were correct. We are testing how well our actual counts ‘fit’ the expected values.</p>
<p>In a typical software implementation of the test, such as in R, we give it the counts we actually got for each possible outcome and also the expected proportion for each outcome. The test then gives us a p-value, a probability, for how likely it is that we would have got the counts we actually got, or counts even furthe from the null hypothesis, if that null hypothesis were correct. If this p-value is too small, and usually, by that we mean less than 0.05, then we reject the null hypothesis.</p>
<div id="example" class="section level3 hasAnchor" number="2.1.1">
<h3><span class="header-section-number">2.1.1</span> Example<a href="chi-square.html#example" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Suppose we have crossed pea plants that were all heterozygous for yellow/green pea colour. In the F1 generation we get 176 offspring , of which 130 were yellow and 46 were green.</p>
<p>The data here are raw counts, and an individual pea plant offspring contributes either to the yellow count or to the green count, but not to both.</p>
<p>Our expected counts of yellow and green are found by simply dividing the total count of offspring, 176, in the ratio 3:1, giving us an expected 132 yellow pea plants and an expected 44 green pea plants in the offspring F1 generation.</p>
</div>
<div id="doing-the-chi-square-test-in-r" class="section level3 hasAnchor" number="2.1.2">
<h3><span class="header-section-number">2.1.2</span> Doing the chi-square test in R<a href="chi-square.html#doing-the-chi-square-test-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>What we do in R is use the <code>chisq.test()</code> command to see how likely it is we would have got counts of 130 and 46 if the null hypothesis, with its expected counts in the ratio 3:1, were true.</p>
<p>We do it like this:</p>
<pre><code>chisq.test(c(130,46),p=c(0.75,0.25))</code></pre>
<p>There are two arguments. The first is the counts we got, which we enter as a ‘vector’ <code>c(z,y,....)</code>, so we write <code>c(130,46)</code>. The second is a vector of the proportions we expect for the two counts, where these proportions should add up to one. So for our expected 3:1 ratio we enter <code>c(0.75,0.25)</code>.</p>
<p>Let’s do it: type the above command into the console window (bottom left). You will get an output something like this:</p>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  c(130, 46)
## X-squared = 0.12121, df = 1, p-value = 0.7277</code></pre>
<p>This output is typical of tests done in R. We get the ‘test statistic’ whose name varies depending on the test. Here it is called <code>X-squared</code>, pronounced <code>chi-squared</code>. This is a number that the test calculates, based on the data you have given it. For the most part, we don’t need to worry about how it does that. Then there is the p-value, which is the probability of getting this test statistic if the null hypothesis were true.</p>
<p>In this case, we see that the p-value is 0.73, which is large. We could very plausibly have got yellow:green numbers of 130 and 46 if the null hypothesis were true, so we cannot reject that null hypothesis. In other words, our data are consistent with the predictions of simple Mendelian inheritance.</p>
</div>
<div id="reporting-the-result-in-english" class="section level3 hasAnchor" number="2.1.3">
<h3><span class="header-section-number">2.1.3</span> Reporting the result in English<a href="chi-square.html#reporting-the-result-in-english" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In English, we might report this result as:</p>
<p><em>We found counts of 130 yellow plants and 46 green plants, which are consistent with the predictions of Mendelian inheritance (chi-squared test, X-squared = 0.12, p=0.73).</em></p>
<p>Note that we do not say we have proved Mendelian inheritance to be correct. We haven’t. We never prove things in science. We haven’t said anything about the truth of the null hypothesis. All we can say is whether our data are or are not consistent with the null hypothesis. In this case they are. We then report the test we used and the values of the test statistic and p-value. Other tests might give you other details to report too.</p>
</div>
</div>
<div id="exercise-1." class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Exercise 1.<a href="chi-square.html#exercise-1." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Suppose you tossed a fair coin 100 times and got 45 heads and 55 tails.</p>
<ul>
<li>Under a null hypothesis that the coin is fair, what would the expected numbers of heads and tails be?</li>
</ul>
<p>You use R to do a chi-square test of that null hypothesis. Here is the code to do that and the output it would give:</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="chi-square.html#cb46-1" tabindex="-1"></a><span class="fu">chisq.test</span>(<span class="fu">c</span>(<span class="dv">45</span>,<span class="dv">55</span>),<span class="at">p=</span><span class="fu">c</span>(<span class="fl">0.5</span>,<span class="fl">0.5</span>)) <span class="co"># we could leave out the second argument here</span></span></code></pre></div>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  c(45, 55)
## X-squared = 1, df = 1, p-value = 0.3173</code></pre>
<ul>
<li><p>What do you conclude?</p></li>
<li><p>How would you report the result?</p></li>
</ul>
<div id="solution.-1" class="section level3 hasAnchor" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> Solution. 1<a href="chi-square.html#solution.-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The expectation is that half the outcomes would be heads and half would be tails.</p>
<pre><code>## 
##  Chi-squared test for given probabilities
## 
## data:  c(45, 55)
## X-squared = 1, df = 1, p-value = 0.3173</code></pre>
<p>The null hypothesis of this test is that heads and tails are equally likely, ie that the coin is fair. Under this null hypothesis the expected outcome is 50 heads and 50 tails. From the output of the R code we see that the p-value, the probability of getting an outcome as far or further from that, is 0.317. That is pretty high. Would you do anything if you knew that the probability of a bad (or worse) outcome was 0.317? In particular, this p-value is greater than 0.05, so we cannot reject the null hypothesis that the coin is fair. That is, even with a fair coin it is not at all unlikely that you would get head/tail numbers as different from 50/50 as 45/55 if you tossed the coin 100 times. That will happen about 1/3 of the time if you repeatedly do trials where you toss the coin 100 times.</p>
<p>To report this result, you might say something like</p>
<p><em>From 100 coin tosses we got 45 heads and 55 tails. These counts are consistent with the coin being fair (chi-squared test, X-squared = 1, p=0.317).</em></p>
</div>
</div>
<div id="way-chi-square-analysis-test-of-independence" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> 2-way chi square analysis: test of independence<a href="chi-square.html#way-chi-square-analysis-test-of-independence" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><em>Taken from Chapter 5: Beckerman, Childs and Petchey: Getting Started with R</em></p>
<p>A common scenario where we have count data is that there are two explanatory factors each with two or more levels that enable us to classify the data. This can happen when something is either true or not true, and a test for for this truth gives either a positive or a negative result. We might want to know if the test to determine truth was any better than flippig a coin: is there some association between what the truth is (eg I do or do not have a disease) and what the test says about that (testing positive or negative for the disease). Our data would be counts of people in each of four categories: have the disease / test positive, have the disease / test negative, do not have the disease / test positive and do not have the disease / test negative.</p>
<p>We are going to analyse another scenario to see if there is evidence for an association between two factors. We have some count data of ladybirds found in an industrial and in a rural location. Some of the ladybirds are red and some are black. We would like to test for whether there is an association between the ladybird colour and its location. If there isn’t then we would expect the proportion of black to red ladybirds to be roughly the same in both habitats. If there is, then we would expect the proportions to be different, meaning that knowing the habitat would tell us something about the likelihood of a ladybird found there being black or red.</p>
<p>Behind this the research purpose might be to investigate whether matching of morphological colour of the ladybirds to the prevalent colour of the environment confers an evolutionary advantage. If it does then we would expect there to be an association between morphological colour and environment so that the proportion of black to red ladybirds would be higher in a grimy industrial setting than in it would be in a rural setting.</p>
<p>We will use a <strong>Chi-Square contingency analysis</strong> to investigate this. This type of analysis is used when you have</p>
<ul>
<li>Count data - how many red ladybirds in a rural setting, how many in an industrial setting, how many black ladydbirds in each of the settings?</li>
<li>Enough count data - typically at least 5 individuals for each combination of the levels in question, which would be rural/red, rural/black, industrial/red and industrial/black in this case.</li>
<li>Independent counts - each ladybird contributes to only one total. For example, if it is red and found in a rural location, then it contributes to the count of red ladybirds found in a rural location, and not to any other sub-total, such as black ladybirds found in a rural location.</li>
</ul>
<div id="hypotheses" class="section level3 hasAnchor" number="2.3.1">
<h3><span class="header-section-number">2.3.1</span> Hypotheses<a href="chi-square.html#hypotheses" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>What do you think a suitable hypothesis should be for this investigation, and what would the corresponding null hypothesis be?</p>
<ul>
<li>The null hypotheses could be: <strong>H<sub>0</sub></strong>: There is no association between habitat and ladybird colour. This means that whatever the proportion is of black to red ladybirds, it is the same in both habitats.<br />
</li>
<li>The alternate hypothesis could be: <strong>H1</strong>: There is an association between habitat and ladybird colour.</li>
</ul>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="chi-square.html#cb49-1" tabindex="-1"></a><span class="co"># Load packages we need</span></span>
<span id="cb49-2"><a href="chi-square.html#cb49-2" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb49-3"><a href="chi-square.html#cb49-3" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb49-4"><a href="chi-square.html#cb49-4" tabindex="-1"></a><span class="fu">library</span>(cowplot) <span class="co"># this makes your plots look nicer</span></span>
<span id="cb49-5"><a href="chi-square.html#cb49-5" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb49-6"><a href="chi-square.html#cb49-6" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_cowplot</span>()) <span class="co"># this sets the cowplot theme to be the default theme.</span></span></code></pre></div>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="chi-square.html#cb50-1" tabindex="-1"></a><span class="co"># Import the data</span></span>
<span id="cb50-2"><a href="chi-square.html#cb50-2" tabindex="-1"></a>filepath<span class="ot">&lt;-</span><span class="fu">here</span>(<span class="st">&quot;data&quot;</span>,<span class="st">&quot;ladybirds_morph_colour.csv&quot;</span>)</span>
<span id="cb50-3"><a href="chi-square.html#cb50-3" tabindex="-1"></a>lady<span class="ot">&lt;-</span><span class="fu">read_csv</span>(filepath)</span>
<span id="cb50-4"><a href="chi-square.html#cb50-4" tabindex="-1"></a><span class="co">#glimpse(lady)</span></span></code></pre></div>
</div>
<div id="summarise-the-data." class="section level3 hasAnchor" number="2.3.2">
<h3><span class="header-section-number">2.3.2</span> Summarise the data.<a href="chi-square.html#summarise-the-data." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The data consist of counts of the number of ladybirds of each colour that were observed in 10 rural locations and 10 industrial locations.</p>
<p>Here is a summary of that data:</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="chi-square.html#cb51-1" tabindex="-1"></a>lady.mat<span class="ot">&lt;-</span><span class="fu">xtabs</span>(number<span class="sc">~</span>Habitat <span class="sc">+</span> morph_colour, <span class="at">data=</span>lady)</span>
<span id="cb51-2"><a href="chi-square.html#cb51-2" tabindex="-1"></a>lady.mat</span></code></pre></div>
<pre><code>##             morph_colour
## Habitat      black red
##   Industrial   115  85
##   Rural         30  70</code></pre>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="chi-square.html#cb53-1" tabindex="-1"></a><span class="co"># Calculate the totals of each colour in each habitat.</span></span>
<span id="cb53-2"><a href="chi-square.html#cb53-2" tabindex="-1"></a>totals<span class="ot">&lt;-</span> lady <span class="sc">|&gt;</span></span>
<span id="cb53-3"><a href="chi-square.html#cb53-3" tabindex="-1"></a>  <span class="fu">group_by</span>(Habitat,morph_colour) <span class="sc">|&gt;</span></span>
<span id="cb53-4"><a href="chi-square.html#cb53-4" tabindex="-1"></a>  <span class="fu">summarise</span> (<span class="at">total.number =</span> <span class="fu">sum</span>(number))</span>
<span id="cb53-5"><a href="chi-square.html#cb53-5" tabindex="-1"></a><span class="co"># totals |&gt;</span></span>
<span id="cb53-6"><a href="chi-square.html#cb53-6" tabindex="-1"></a><span class="co">#   kbl() |&gt;</span></span>
<span id="cb53-7"><a href="chi-square.html#cb53-7" tabindex="-1"></a><span class="co">#   kable_styling(full_width=FALSE)</span></span>
<span id="cb53-8"><a href="chi-square.html#cb53-8" tabindex="-1"></a>totals</span></code></pre></div>
<pre><code>## # A tibble: 4 × 3
## # Groups:   Habitat [2]
##   Habitat    morph_colour total.number
##   &lt;chr&gt;      &lt;chr&gt;               &lt;dbl&gt;
## 1 Industrial black                 115
## 2 Industrial red                    85
## 3 Rural      black                  30
## 4 Rural      red                    70</code></pre>
</div>
<div id="plot-the-data." class="section level3 hasAnchor" number="2.3.3">
<h3><span class="header-section-number">2.3.3</span> Plot the data.<a href="chi-square.html#plot-the-data." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now that we have these totals we can use them to plot a bar chart of the data:</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="chi-square.html#cb55-1" tabindex="-1"></a><span class="co"># plot the data, with sensible colours</span></span>
<span id="cb55-2"><a href="chi-square.html#cb55-2" tabindex="-1"></a>totals <span class="sc">|&gt;</span></span>
<span id="cb55-3"><a href="chi-square.html#cb55-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Habitat,<span class="at">y =</span> total.number,<span class="at">fill=</span>morph_colour))<span class="sc">+</span></span>
<span id="cb55-4"><a href="chi-square.html#cb55-4" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position=</span><span class="st">&#39;dodge&#39;</span>) <span class="sc">+</span></span>
<span id="cb55-5"><a href="chi-square.html#cb55-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&quot;Habitat&quot;</span>,</span>
<span id="cb55-6"><a href="chi-square.html#cb55-6" tabindex="-1"></a>       <span class="at">y=</span><span class="st">&quot;Count&quot;</span>,</span>
<span id="cb55-7"><a href="chi-square.html#cb55-7" tabindex="-1"></a>       <span class="at">fill=</span> <span class="st">&quot;Colour&quot;</span>) <span class="sc">+</span></span>
<span id="cb55-8"><a href="chi-square.html#cb55-8" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values=</span><span class="fu">c</span>(<span class="at">black=</span><span class="st">&#39;#312626&#39;</span>,<span class="at">red=</span><span class="st">&#39;#da1717&#39;</span>)) <span class="sc">+</span> <span class="co"># this line manually sets the colours for us</span></span>
<span id="cb55-9"><a href="chi-square.html#cb55-9" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position=</span><span class="st">&quot;none&quot;</span>)</span></code></pre></div>
<p><img src="chi-square_files/figure-html/unnamed-chunk-10-1.png" width="672" style="display: block; margin: auto;" /></p>
</div>
<div id="interpret-the-graph-before-we-do-any-stats" class="section level3 hasAnchor" number="2.3.4">
<h3><span class="header-section-number">2.3.4</span> Interpret the graph before we do any ‘stats’<a href="chi-square.html#interpret-the-graph-before-we-do-any-stats" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Look at the plot - does it look as though the proportion of black to red ladybirds is the same in the two habitats? Do you expect to retain or to reject the null hypothesis, which says that there is no association between habitat and ladybird colour, and hence that the proportions are the same?</p>
</div>
<div id="the-chi-square-test" class="section level3 hasAnchor" number="2.3.5">
<h3><span class="header-section-number">2.3.5</span> The Chi-square test<a href="chi-square.html#the-chi-square-test" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To do a chi square test, it helps to set out these data as a 2 x 2 table:</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="chi-square.html#cb56-1" tabindex="-1"></a>lady.mat<span class="ot">&lt;-</span><span class="fu">xtabs</span>(number<span class="sc">~</span>Habitat <span class="sc">+</span> morph_colour, <span class="at">data=</span>lady)</span>
<span id="cb56-2"><a href="chi-square.html#cb56-2" tabindex="-1"></a>lady.mat</span></code></pre></div>
<pre><code>##             morph_colour
## Habitat      black red
##   Industrial   115  85
##   Rural         30  70</code></pre>
<p>This kind of table is sometimes called a <strong>contingency table</strong>.</p>
<p>When we give these numbers to some statistical software such as R and ask it to carry out a ‘chi-square test’ it will use the data to calculate a ‘test statistic’ <span class="math inline">\(X^2\)</span> by comparing the actual counts of the ladybirds in the table above with their expected counts under the null hypothesis. The further the actual counts are from their expected values, on the whole, the bigger this test statistic will be. For the gory (they are not that gory!) details on how this done, see the section below but do note that, while these are interesting, if you find that kind of thing interesting, as I do, you do not need to be familiar with them to be able to apply a chi-square test. What you do need to know is when it is OK to use one, and when it is not, as is true for any statistical test.</p>
<p>We’ll turn to that issue now:</p>
<p>Providing a number of conditions are met by the data (principally, that they are count data, that all the cell values are greater than or equal to about five and that they are all independent ie any ladybird contributes to the count of only one cell), this test statistic <span class="math inline">\(X^2\)</span> has a so-called ‘chi-squared’ distribution. This is a known mathematical distribution, which makes it possible to calculate the probability that the statistic would be as big as it is, or bigger, if the null hypothesis were true. We call this probability the <em>p</em>-value.</p>
<p>This is generally how statistical tests work. They take your data and use it in a carefully chosen way to calculate some number that in general is called a <em>test statistic</em> but which is referred to by different names when calculated for particular tests. How it is calculated depends on the test and these days we never have to do the calculations. That’s taken care of by software like R. Providing the data meet certain criteria, the statistic will typically have a probability distribution. This means that the probability that it will exceed a given value if the null hypothesis is true can be calculated. This probability is the <em>p</em>-value. If the <em>p</em>-value is very small, and by that we typically mean less than 0.05 or 0.01, then we can reject the null hypothesis.</p>
<p>When we run a chi-square test in R on the data in the table above it gives us this as output:</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="chi-square.html#cb58-1" tabindex="-1"></a><span class="fu">chisq.test</span>(lady.mat)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test with Yates&#39; continuity correction
## 
## data:  lady.mat
## X-squared = 19.103, df = 1, p-value = 1.239e-05</code></pre>
</div>
<div id="yates-continuity-correction" class="section level3 hasAnchor" number="2.3.6">
<h3><span class="header-section-number">2.3.6</span> Yates continuity correction<a href="chi-square.html#yates-continuity-correction" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>This adjusts for the fact that our data are discrete and the chi-square distribution that we are using to calculate the <em>p</em>-values is continuous. That’s it.</p>
</div>
<div id="conclusion" class="section level3 hasAnchor" number="2.3.7">
<h3><span class="header-section-number">2.3.7</span> Conclusion<a href="chi-square.html#conclusion" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Study the output of the chi-square test. Note that you are given a test-statistic (here called Chi-squared/X-squared) and a number of degrees of freedom (<em>df</em>) (in some tests you are given more than one of these). This is the number of independent pieces of information used to calculate the test statistic. Lastly, you are a given a <em>p</em>-value. This is the probability that you would have got a chi-squared value as big or bigger than the one you got <em>if</em> the null hypothesis were true. Here the null hypothesis is that there is no association between ladybird colour and location. Put another way, it is, roughly speaking the probability of getting the data you actually got if the null hypothesis were true.</p>
<p>An appropriate way to report these data would be:</p>
<p>‘Ladybird colour morphs are not equally common in the two habitats (Chi-sq =19.3, df = 1, p&lt;0.001)’</p>
</div>
</div>
<div id="the-chi-square-test-explained-advanced" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> The Chi-Square Test explained (advanced)<a href="chi-square.html#the-chi-square-test-explained-advanced" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>You can skip this section if you are not interested in how the chi-square test works. If you are, read on.</p>
<p>Let’s recall the number of sightings of each colour of ladybird in each habitat:</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="chi-square.html#cb60-1" tabindex="-1"></a>lady.mat</span></code></pre></div>
<pre><code>##             morph_colour
## Habitat      black red
##   Industrial   115  85
##   Rural         30  70</code></pre>
<p>If there were no association between colour and habitat, then we would expect the relative proportions of colour to be independent of habitat. That is they should be the same in both rural and industrial habitats. Looking at the table above we see that two thirds (200 out of 300) of all sightings, regardless of colour, were in an industrial habitat. Hence we would expect that two thirds of all 145 black sightings would be in an industrial habitat. We thus arrive at an ‘expected’ number for sightings of black butterflies in an industrial habitat to be <span class="math inline">\((200/300) \times 145 = 96.7\)</span>. Similarly, we would expect one third (100 out of 300) of all 155 red sightings to be in a rural habitat, giving an ‘expected’ number for this combination of levels to be <span class="math inline">\((100/300)\times 155 = 51.7\)</span>. More generally, the expected number in an any cell of the table, under the null hypothesis of no association between the two factors is given by</p>
<p><span class="math display">\[\text{expected number}=\frac{\text{row total}\times\text{column total}}{\text{grand total}}\]</span>
Using this method, these are the four expected numbers for each combination of levels of the two factors we have:</p>
<pre><code>##       [,1]   [,2]
## [1,] 96.67 103.33
## [2,] 48.33  51.67</code></pre>
<p>To get a measurement of how far the actual table numbers are from their expected values we can, for each cell, square the difference between the expected and actual values, then divide the result by the actual value, and finally sum the four results that we get. This has the effect of giving equal weight to positive or negative deviations of the observed values from the expected values, and scales each squared deviation so that all four have equal weight in the final sum. The result is the chi-squared test statistic:</p>
<p><span class="math display">\[
\begin{align*}
X^2&amp;=\sum_{i=1}^4\frac{(O_i-E_i)^2}{E_i}\\
&amp;=\frac{(115-96.67)^2}{96.67} + \frac{(85-103.33)^2}{103.33} + \frac{(30-48.33)^2}{48.33} + \frac{(70-51.67)^2}{51.67}\\
&amp;=20.189
\end{align*}
\]</span></p>
<p><strong>Yates continuity correction</strong> (digression)</p>
<p>You may have noticed that the <span class="math inline">\(X^2 = 20.189\)</span> value calculated above is slightly larger than the value calculated by the <code>chisq.test()</code> function, which found <span class="math inline">\(X^2 = 19.096\)</span>. This is because the function uses Yates continuity correction. This was suggested by Yates in 1934 to correct for the fact that the <span class="math inline">\(X^2\)</span> statistic we calculate is actually discrete (becuase we have categorical data) whereas the chi-square distribution is continuous. This means that the value we calculate tends to be too big so that our <em>p</em>-values are too small. The problem is most apparent where we have small numbers and one degree of freedom, which is what you have in a <span class="math inline">\(2 \times 2\)</span> contigency table such s in the example above. Yates’ fix is quite simple: just amend the <span class="math inline">\(X^2\)</span> statistic to the following:</p>
<p><span class="math display">\[
X^2=\sum_{i=1}^4\frac{(\lvert O_i-E_i \rvert - 0.5)^2}{E_i}
\]</span></p>
<p>where the vertical lines mean ‘take the absolute value of’, so that |85-103.33| = |-18.33| = 18.33</p>
<p>This gives us</p>
<p><span class="math display">\[
\begin{align*}
X^2&amp;=\sum_{i=1}^4\frac{(\lvert O_i-E_i \rvert - 0.5)^2}{E_i}\\
&amp;=\frac{(|115-96.67|-0.5)^2}{96.67} + \frac{(|85-103.33|-0.5)^2}{103.33} + \frac{(|30-48.33|-0.5)^2}{48.33} + \frac{(|70-51.67|-0.5)^2}{51.67}\\
&amp;=19.096
\end{align*}
\]</span>
which is exactly what the <code>chisq.test()</code> function gives.</p>
<p>Under a null hypothesis of no association between habitat and colour all the counts would be the ‘expected’ values, and <span class="math inline">\(X^2\)</span> would be zero. The further away from these values the actual results are, the bigger <span class="math inline">\(X^2\)</span> will be and the more likely it is that we can reject the null. For a sufficiently large value of <span class="math inline">\(X^2\)</span> we <em>will</em> reject the null. To sum up, in general we will reject the null when <span class="math inline">\(X^2\)</span> is large, and fail to reject it when it is small.</p>
<p>But how large is large enough to reject the null?</p>
<p>To answer this we use the fact that the sampling distribution of <span class="math inline">\(X^2\)</span> is a chi-squared distribution with (in this case) <span class="math inline">\((2-1) \times (2-1) = 1\)</span> degrees of freedom.</p>
<p>The p-value given in a chi-square test is the probability of getting a chi-squared statistic <span class="math inline">\(X^2\)</span> as big as or bigger than the one you actually got. This is the area under the chi-squared distribution with the appropriate number of degrees of freedom to the right of the test-statistic value <span class="math inline">\(X^2\)</span>.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="chi-square.html#cb63-1" tabindex="-1"></a>xsquared<span class="ot">&lt;-</span><span class="fl">19.1</span></span>
<span id="cb63-2"><a href="chi-square.html#cb63-2" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">20</span>)), <span class="fu">aes</span>(<span class="at">x =</span> x)) <span class="sc">+</span> </span>
<span id="cb63-3"><a href="chi-square.html#cb63-3" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> dchisq, <span class="at">args =</span> <span class="fu">list</span>(<span class="at">df =</span> <span class="dv">1</span>)) <span class="sc">+</span> </span>
<span id="cb63-4"><a href="chi-square.html#cb63-4" tabindex="-1"></a>  <span class="fu">stat_function</span>(<span class="at">fun =</span> dchisq, <span class="at">args =</span> <span class="fu">list</span>(<span class="at">df =</span> <span class="dv">1</span>), <span class="at">xlim =</span> <span class="fu">c</span>(xsquared, <span class="dv">20</span>),</span>
<span id="cb63-5"><a href="chi-square.html#cb63-5" tabindex="-1"></a>                  <span class="at">geom =</span> <span class="st">&quot;area&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;#84CA72&quot;</span>, <span class="at">alpha =</span> .<span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb63-6"><a href="chi-square.html#cb63-6" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">name =</span> <span class="st">&quot;&quot;</span>, <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">20</span>,<span class="dv">2</span>)) <span class="sc">+</span></span>
<span id="cb63-7"><a href="chi-square.html#cb63-7" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept=</span>xsquared,<span class="at">linewidth=</span><span class="fl">0.2</span>,<span class="at">colour=</span><span class="st">&quot;gray80&quot;</span>) <span class="sc">+</span></span>
<span id="cb63-8"><a href="chi-square.html#cb63-8" tabindex="-1"></a>  <span class="fu">theme_cowplot</span>()</span></code></pre></div>
<p><img src="chi-square_files/figure-html/unnamed-chunk-17-1.png" width="672" style="display: block; margin: auto;" /></p>
<div id="why-does-the-test-statistic-have-this-distribution" class="section level3 hasAnchor" number="2.4.1">
<h3><span class="header-section-number">2.4.1</span> Why does the test statistic have this distribution?<a href="chi-square.html#why-does-the-test-statistic-have-this-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To answer this, let us recognise that in our observed contingency table, where we have <em>N</em> observations altogether, we can think of their being a probability <span class="math inline">\(P_i\)</span> that any individual observation will end up in cell <em>i</em>, with the actual observed frequency in that cell, <span class="math inline">\(O_i\)</span> being the product of this probability and the total number of observations: <span class="math inline">\(O_i = P_i\times N\)</span>. If we repeated the study again and again we would get slightly different numbers in each cell each time. The distribution of the numbers in a particular cell would follow similar rules as that of the number of heads we might get each time if we tossed a coin <em>N</em> times, then did the same again and again. This distribution is called a <em>binomial distribution</em>.</p>
<p>In other words, our observed frequencies have been obtained by sampling from a binomial distribution, where <span class="math inline">\(O_i \sim \text{Binomial}(P_i,N)\)</span>. Now, providing <em>N</em> is large enough and providing too that the probabilities <span class="math inline">\(P_i\)</span> are not too close to 0 or 1, then the binomial distribution resembles a normal distribution. Thus, providing <span class="math inline">\(P_i\times N\)</span>, that is providing the observed frequencies <span class="math inline">\(O_i=P_i\times N\)</span> are large enough, then the <span class="math inline">\(O_i\)</span> will be approximately normally distributed.If this is the case, then so too is <span class="math inline">\(\frac{(O_i-E_i)}{\sqrt{E_i}}\)</span> since the expected values <span class="math inline">\(E_i\)</span> are fixed quantities and all this transformation does is turn our normal distribution into a <em>standard</em> normal distribution, with mean = 0 and standard deviation = 1. ie it shifts and squishes the distribution.</p>
<p>Hence in our expression for our test statistic <span class="math inline">\(X^2\)</span> what we are doing is adding up <em>k</em> (= 4 in this case) squared standard normal distributions. This is the definition of a chi-squared distribution with four degrees of freedom. Thus we see that the sampling distribution of our test statistic is a chi-squared distribution.</p>
<p>The one final slightly odd detail is that when we run a chi-square test for a 2 x 2 contingency table we are told that there is one degree of freedom. In general, for <span class="math inline">\(m \times  n\)</span> table, there will be <span class="math inline">\((m-1)\times(n-1)\)</span> degrees of freedom. This is because the test presumes that the row and column total are already known. If that is the case then if one value of a 2x2 table is known, the other 3 values can be found by deduction. Hence there only one value (it doesn’t matter which one) can be chosen freely.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="plot-with-ggplot.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="fishers-exact-test.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/Newquay-University-Centre/r4nqy/edit/main/chi-square.Rmd",
"text": "Suggest an edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["https://github.com/Newquay-University-Centre/r4nqy/raw/main/chi-square.Rmd"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
