<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 8 Simple linear regression | ANOVA: Factorial experiments and model simplification</title>
  <meta name="description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="generator" content="bookdown 0.39 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 8 Simple linear regression | ANOVA: Factorial experiments and model simplification" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 8 Simple linear regression | ANOVA: Factorial experiments and model simplification" />
  
  <meta name="twitter:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  

<meta name="author" content="Michael Hunt" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="one-way-anova.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> About</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#usage"><i class="fa fa-check"></i><b>1.1</b> Usage</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#render-book"><i class="fa fa-check"></i><b>1.2</b> Render book</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#preview-book"><i class="fa fa-check"></i><b>1.3</b> Preview book</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="plot-your-data.html"><a href="plot-your-data.html"><i class="fa fa-check"></i><b>2</b> Plot your data</a>
<ul>
<li class="chapter" data-level="2.0.1" data-path="plot-your-data.html"><a href="plot-your-data.html#load-packages"><i class="fa fa-check"></i><b>2.0.1</b> Load packages</a></li>
<li class="chapter" data-level="2.0.2" data-path="plot-your-data.html"><a href="plot-your-data.html#get-the-template-script"><i class="fa fa-check"></i><b>2.0.2</b> Get the template script</a></li>
<li class="chapter" data-level="2.0.3" data-path="plot-your-data.html"><a href="plot-your-data.html#load-the-palmer-penguin-data"><i class="fa fa-check"></i><b>2.0.3</b> Load the Palmer penguin data</a></li>
<li class="chapter" data-level="2.0.4" data-path="plot-your-data.html"><a href="plot-your-data.html#summary-stats-on-all-the-numeric-columns"><i class="fa fa-check"></i><b>2.0.4</b> Summary stats on all the numeric columns</a></li>
<li class="chapter" data-level="2.0.5" data-path="plot-your-data.html"><a href="plot-your-data.html#remove-the-rows-with-nas"><i class="fa fa-check"></i><b>2.0.5</b> Remove the rows with NAs</a></li>
<li class="chapter" data-level="2.0.6" data-path="plot-your-data.html"><a href="plot-your-data.html#how-many-observations-are-there-for-each-species"><i class="fa fa-check"></i><b>2.0.6</b> How many observations are there for each species?</a></li>
<li class="chapter" data-level="2.0.7" data-path="plot-your-data.html"><a href="plot-your-data.html#mean-value-for-each-numerical-variable-for-each-species"><i class="fa fa-check"></i><b>2.0.7</b> Mean value for each numerical variable, for each species</a></li>
<li class="chapter" data-level="2.0.8" data-path="plot-your-data.html"><a href="plot-your-data.html#scatter-plots"><i class="fa fa-check"></i><b>2.0.8</b> Scatter plots</a></li>
<li class="chapter" data-level="2.0.9" data-path="plot-your-data.html"><a href="plot-your-data.html#repeat-for-bill-length-and-flipper-length"><i class="fa fa-check"></i><b>2.0.9</b> Repeat for bill length and flipper length</a></li>
<li class="chapter" data-level="2.0.10" data-path="plot-your-data.html"><a href="plot-your-data.html#add-yet-more-informtion-to-the-plot"><i class="fa fa-check"></i><b>2.0.10</b> Add yet more informtion to the plot</a></li>
<li class="chapter" data-level="2.0.11" data-path="plot-your-data.html"><a href="plot-your-data.html#distribution-of-penguin-flipper-lengths"><i class="fa fa-check"></i><b>2.0.11</b> Distribution of penguin flipper lengths</a></li>
<li class="chapter" data-level="2.0.12" data-path="plot-your-data.html"><a href="plot-your-data.html#bar-chart-with-error-bar"><i class="fa fa-check"></i><b>2.0.12</b> Bar chart with error bar</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="correlation.html"><a href="correlation.html"><i class="fa fa-check"></i><b>3</b> Correlation</a></li>
<li class="chapter" data-level="4" data-path="section.html"><a href="section.html"><i class="fa fa-check"></i><b>4</b> </a>
<ul>
<li class="chapter" data-level="4.1" data-path="section.html"><a href="section.html#correlation-1"><i class="fa fa-check"></i><b>4.1</b> Correlation</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="section.html"><a href="section.html#the-correlation-coefficient"><i class="fa fa-check"></i><b>4.1.1</b> The correlation coefficient</a></li>
<li class="chapter" data-level="4.1.2" data-path="section.html"><a href="section.html#different-values-of-r."><i class="fa fa-check"></i><b>4.1.2</b> Different values of <em>r</em>.</a></li>
<li class="chapter" data-level="4.1.3" data-path="section.html"><a href="section.html#using-r-to-find-the-correlation-coefficient."><i class="fa fa-check"></i><b>4.1.3</b> Using R to find the correlation coefficient.</a></li>
<li class="chapter" data-level="4.1.4" data-path="section.html"><a href="section.html#correlations-for-real-data"><i class="fa fa-check"></i><b>4.1.4</b> Correlations for real data</a></li>
<li class="chapter" data-level="4.1.5" data-path="section.html"><a href="section.html#the-correlation-coefficient-measures-the-degree-of-linear-association."><i class="fa fa-check"></i><b>4.1.5</b> The correlation coefficient measures the degree of linear association.</a></li>
<li class="chapter" data-level="4.1.6" data-path="section.html"><a href="section.html#when-is-it-appropriate-to-calculate-a-correlation-coefficient"><i class="fa fa-check"></i><b>4.1.6</b> When is it appropriate to calculate a correlation coefficient?</a></li>
<li class="chapter" data-level="4.1.7" data-path="section.html"><a href="section.html#association-is-not-causation"><i class="fa fa-check"></i><b>4.1.7</b> Association is not causation</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="section.html"><a href="section.html#examples"><i class="fa fa-check"></i><b>4.2</b> Examples</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="section.html"><a href="section.html#lichen-abundance"><i class="fa fa-check"></i><b>4.2.1</b> Lichen abundance</a></li>
<li class="chapter" data-level="4.2.2" data-path="section.html"><a href="section.html#soil-bacteria"><i class="fa fa-check"></i><b>4.2.2</b> Soil bacteria</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="section.html"><a href="section.html#exercise-1"><i class="fa fa-check"></i><b>4.3</b> Exercise 1</a></li>
<li class="chapter" data-level="4.4" data-path="section.html"><a href="section.html#exercise-2"><i class="fa fa-check"></i><b>4.4</b> Exercise 2</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="t-test-for-difference.html"><a href="t-test-for-difference.html"><i class="fa fa-check"></i><b>5</b> t-test for difference</a>
<ul>
<li class="chapter" data-level="5.0.1" data-path="t-test-for-difference.html"><a href="t-test-for-difference.html#preliminaries"><i class="fa fa-check"></i><b>5.0.1</b> Preliminaries</a></li>
<li class="chapter" data-level="5.0.2" data-path="t-test-for-difference.html"><a href="t-test-for-difference.html#motivation-and-example"><i class="fa fa-check"></i><b>5.0.2</b> Motivation and example</a></li>
<li class="chapter" data-level="5.0.3" data-path="t-test-for-difference.html"><a href="t-test-for-difference.html#the-two-sample-t-test"><i class="fa fa-check"></i><b>5.0.3</b> The two-sample <em>t</em>-test</a></li>
<li class="chapter" data-level="5.0.4" data-path="t-test-for-difference.html"><a href="t-test-for-difference.html#the-workflow"><i class="fa fa-check"></i><b>5.0.4</b> The workflow</a></li>
<li class="chapter" data-level="5.0.5" data-path="t-test-for-difference.html"><a href="t-test-for-difference.html#step-one-summarise-the-data"><i class="fa fa-check"></i><b>5.0.5</b> Step One: Summarise the data</a></li>
<li class="chapter" data-level="5.0.6" data-path="t-test-for-difference.html"><a href="t-test-for-difference.html#step-two-plot-the-data"><i class="fa fa-check"></i><b>5.0.6</b> Step Two: Plot the data</a></li>
<li class="chapter" data-level="5.0.7" data-path="t-test-for-difference.html"><a href="t-test-for-difference.html#step-three-carry-out-statistical-analysis"><i class="fa fa-check"></i><b>5.0.7</b> Step Three: Carry out statistical analysis</a></li>
<li class="chapter" data-level="5.0.8" data-path="t-test-for-difference.html"><a href="t-test-for-difference.html#the-complete-script"><i class="fa fa-check"></i><b>5.0.8</b> The complete script</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html"><i class="fa fa-check"></i><b>6</b> Paired tests for difference</a>
<ul>
<li class="chapter" data-level="6.0.1" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html#which-test-paired-t-test-or-wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>6.0.1</b> Which test: paired t-test or Wilcoxon signed rank test?</a></li>
<li class="chapter" data-level="6.0.2" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html#example"><i class="fa fa-check"></i><b>6.0.2</b> Example</a></li>
<li class="chapter" data-level="6.0.3" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html#the-non-parametric-alternative-the-wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>6.0.3</b> The non-parametric alternative: The Wilcoxon signed rank test</a></li>
<li class="chapter" data-level="6.0.4" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html#factorial-experiments-and-model-simplification"><i class="fa fa-check"></i><b>6.0.4</b> Factorial experiments and model simplification</a></li>
<li class="chapter" data-level="6.0.5" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html#files-needed"><i class="fa fa-check"></i><b>6.0.5</b> Files needed</a></li>
<li class="chapter" data-level="6.0.6" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html#open-your-project-1"><i class="fa fa-check"></i><b>6.0.6</b> Open your Project</a></li>
<li class="chapter" data-level="6.0.7" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html#load-packages-3"><i class="fa fa-check"></i><b>6.0.7</b> Load packages</a></li>
<li class="chapter" data-level="6.0.8" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html#read-in-the-data"><i class="fa fa-check"></i><b>6.0.8</b> Read in the data</a></li>
<li class="chapter" data-level="6.0.9" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html#make-r-recognise-the-categorical-variables-as-factors-and-order-the-levels."><i class="fa fa-check"></i><b>6.0.9</b> Make R recognise the categorical variables as factors, and order the levels.</a></li>
<li class="chapter" data-level="6.0.10" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html#summarise-the-data"><i class="fa fa-check"></i><b>6.0.10</b> Summarise the data</a></li>
<li class="chapter" data-level="6.0.11" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html#plot-the-data-1"><i class="fa fa-check"></i><b>6.0.11</b> Plot the data</a></li>
<li class="chapter" data-level="6.0.12" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html#anova"><i class="fa fa-check"></i><b>6.0.12</b> ANOVA</a></li>
<li class="chapter" data-level="6.0.13" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html#model-simplification"><i class="fa fa-check"></i><b>6.0.13</b> Model Simplification</a></li>
<li class="chapter" data-level="6.0.14" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html#check-the-validity-of-the-linear-model"><i class="fa fa-check"></i><b>6.0.14</b> Check the validity of the linear model</a></li>
<li class="chapter" data-level="6.0.15" data-path="paired-tests-for-difference.html"><a href="paired-tests-for-difference.html#reporting-the-results"><i class="fa fa-check"></i><b>6.0.15</b> Reporting the results</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="one-way-anova.html"><a href="one-way-anova.html"><i class="fa fa-check"></i><b>7</b> One-way ANOVA</a>
<ul>
<li class="chapter" data-level="7.1" data-path="one-way-anova.html"><a href="one-way-anova.html#load-packages-4"><i class="fa fa-check"></i><b>7.1</b> Load packages</a></li>
<li class="chapter" data-level="7.2" data-path="one-way-anova.html"><a href="one-way-anova.html#remove-observations-with-missing-values"><i class="fa fa-check"></i><b>7.2</b> Remove observations with missing values</a></li>
<li class="chapter" data-level="7.3" data-path="one-way-anova.html"><a href="one-way-anova.html#summary---group-by-species-and-sex"><i class="fa fa-check"></i><b>7.3</b> Summary - group by species and sex</a></li>
<li class="chapter" data-level="7.4" data-path="one-way-anova.html"><a href="one-way-anova.html#plot-the-data-2"><i class="fa fa-check"></i><b>7.4</b> Plot the data</a></li>
<li class="chapter" data-level="7.5" data-path="one-way-anova.html"><a href="one-way-anova.html#one-way-anova-1"><i class="fa fa-check"></i><b>7.5</b> One-way ANOVA</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="one-way-anova.html"><a href="one-way-anova.html#null-hypothesis"><i class="fa fa-check"></i><b>7.5.1</b> Null hypothesis</a></li>
<li class="chapter" data-level="7.5.2" data-path="one-way-anova.html"><a href="one-way-anova.html#the-actual-anova"><i class="fa fa-check"></i><b>7.5.2</b> The actual ANOVA</a></li>
<li class="chapter" data-level="7.5.3" data-path="one-way-anova.html"><a href="one-way-anova.html#construct-the-model-1"><i class="fa fa-check"></i><b>7.5.3</b> Construct the model</a></li>
<li class="chapter" data-level="7.5.4" data-path="one-way-anova.html"><a href="one-way-anova.html#is-the-model-valid"><i class="fa fa-check"></i><b>7.5.4</b> Is the model valid?</a></li>
<li class="chapter" data-level="7.5.5" data-path="one-way-anova.html"><a href="one-way-anova.html#the-overall-picture"><i class="fa fa-check"></i><b>7.5.5</b> The overall picture</a></li>
<li class="chapter" data-level="7.5.6" data-path="one-way-anova.html"><a href="one-way-anova.html#the-detailed-picture"><i class="fa fa-check"></i><b>7.5.6</b> The detailed picture</a></li>
<li class="chapter" data-level="7.5.7" data-path="one-way-anova.html"><a href="one-way-anova.html#post-hoc-tsts."><i class="fa fa-check"></i><b>7.5.7</b> Post hoc tsts.</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="one-way-anova.html"><a href="one-way-anova.html#reporting-the-result."><i class="fa fa-check"></i><b>7.6</b> Reporting the Result.</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html"><i class="fa fa-check"></i><b>8</b> Simple linear regression</a>
<ul>
<li class="chapter" data-level="8.0.1" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#simple-linear-regression-1"><i class="fa fa-check"></i><b>8.0.1</b> Simple Linear Regression</a></li>
<li class="chapter" data-level="8.0.2" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#load-packages-5"><i class="fa fa-check"></i><b>8.0.2</b> Load packages</a></li>
<li class="chapter" data-level="8.0.3" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#get-the-data"><i class="fa fa-check"></i><b>8.0.3</b> Get the data</a></li>
<li class="chapter" data-level="8.0.4" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#plot-the-data-3"><i class="fa fa-check"></i><b>8.0.4</b> Plot the data</a></li>
<li class="chapter" data-level="8.0.5" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#make-a-simple-model-using-linear-regression"><i class="fa fa-check"></i><b>8.0.5</b> Make a simple model using linear regression</a></li>
<li class="chapter" data-level="8.0.6" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#check-assumptions"><i class="fa fa-check"></i><b>8.0.6</b> Check assumptions</a></li>
<li class="chapter" data-level="8.0.7" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#interpretation-of-the-model"><i class="fa fa-check"></i><b>8.0.7</b> Interpretation of the model</a></li>
<li class="chapter" data-level="8.0.8" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#back-to-the-figure"><i class="fa fa-check"></i><b>8.0.8</b> Back to the figure</a></li>
<li class="chapter" data-level="8.0.9" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#conclusion"><i class="fa fa-check"></i><b>8.0.9</b> Conclusion</a></li>
<li class="chapter" data-level="8.0.10" data-path="simple-linear-regression.html"><a href="simple-linear-regression.html#sample-script"><i class="fa fa-check"></i><b>8.0.10</b> Sample script</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">ANOVA: Factorial experiments and model simplification</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="simple-linear-regression" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">Chapter 8</span> Simple linear regression<a href="simple-linear-regression.html#simple-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>A class of analytical models that you will use this year and next go under the name <strong>General Linear Models</strong>. They include linear regression, multiple regression, ANOVA, ANCOVA, Pearson correlation and t-tests.</p>
<p>Despite appearances, these models are all fundamentally linear models. They share a common framework for estimation (least squares) and a common set of criteria that the data must satisfy before they can be used. These criteria centre around the idea of normally distributed residuals. An important stage of any analysis that uses linear models is that these assumptions are checked, as part of the <em>Plot</em> -&gt; <em>Model</em> -&gt; <em>Check Assumptions</em> -&gt; <em>Interpret</em> -&gt; <em>Plot again</em> workflow.</p>
<p>Here, we will go through an example of simple linear regression - suitable for trend data where we wish to predict a continuously varying response, given a value of a continuous explanatory variable. As we go we show code snippets from an R script that does this job, and, at the bottom, an example complete script that you could adapt to your own needs.</p>
<div id="simple-linear-regression-1" class="section level3 hasAnchor" number="8.0.1">
<h3><span class="header-section-number">8.0.1</span> Simple Linear Regression<a href="simple-linear-regression.html#simple-linear-regression-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As an example, we ask the question: does plant growth rate depend on soil moisture content?</p>
<p>We predict that more moisture will probably allow higher growth rates. We note that this means there will be a clear relationship between the variables, one that should be apparent if we plot the response (dependent) variable - plant growth rate - against the explanatory (independent) variable - soil moisture content. We note that both the explanatory variable and the dependent variables are <em>continuous</em> - they do not have categories.</p>
<p>What we want to do in linear regression is be able to predict the value of the dependent variable, knowing the value of the independent variable. In practice, this means drawing a ‘best fit’ straight line through the data and determining the intercept and gradient of this line.</p>
</div>
<div id="load-packages-5" class="section level3 hasAnchor" number="8.0.2">
<h3><span class="header-section-number">8.0.2</span> Load packages<a href="simple-linear-regression.html#load-packages-5" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="simple-linear-regression.html#cb120-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb120-2"><a href="simple-linear-regression.html#cb120-2" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb120-3"><a href="simple-linear-regression.html#cb120-3" tabindex="-1"></a><span class="fu">library</span>(ggfortify)</span>
<span id="cb120-4"><a href="simple-linear-regression.html#cb120-4" tabindex="-1"></a><span class="fu">library</span>(cowplot)</span>
<span id="cb120-5"><a href="simple-linear-regression.html#cb120-5" tabindex="-1"></a><span class="co"># un-comment and run the next line if you have not yet installed mbhR.</span></span>
<span id="cb120-6"><a href="simple-linear-regression.html#cb120-6" tabindex="-1"></a><span class="co"># remotes::install_github(&quot;mbh038/mbhR&quot;)</span></span>
<span id="cb120-7"><a href="simple-linear-regression.html#cb120-7" tabindex="-1"></a><span class="fu">library</span>(mbhR)</span></code></pre></div>
</div>
<div id="get-the-data" class="section level3 hasAnchor" number="8.0.3">
<h3><span class="header-section-number">8.0.3</span> Get the data<a href="simple-linear-regression.html#get-the-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We have a data set to explore our question: The <code>plants</code> data set is available through the <code>mbhR</code> package which you have already installed and loaded</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="simple-linear-regression.html#cb121-1" tabindex="-1"></a><span class="fu">data</span>(plants)</span>
<span id="cb121-2"><a href="simple-linear-regression.html#cb121-2" tabindex="-1"></a><span class="fu">glimpse</span>(plants)</span></code></pre></div>
<pre><code>## Rows: 50
## Columns: 2
## $ soil.moisture.content &lt;dbl&gt; 0.4696876, 0.5413106, 1.6979915, 0.8255799, 0.85…
## $ plant.growth.rate     &lt;dbl&gt; 21.31695, 27.03072, 38.98937, 30.19529, 37.06547…</code></pre>
<p>We see that the data set contains two continuous variables, as expected.</p>
</div>
<div id="plot-the-data-3" class="section level3 hasAnchor" number="8.0.4">
<h3><span class="header-section-number">8.0.4</span> Plot the data<a href="simple-linear-regression.html#plot-the-data-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can use the package <code>ggplot2</code>, which is part of <code>tidyverse</code> to do this:</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="simple-linear-regression.html#cb123-1" tabindex="-1"></a>plants <span class="sc">|&gt;</span></span>
<span id="cb123-2"><a href="simple-linear-regression.html#cb123-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>soil.moisture.content, <span class="at">y=</span>plant.growth.rate)) <span class="sc">+</span></span>
<span id="cb123-3"><a href="simple-linear-regression.html#cb123-3" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb123-4"><a href="simple-linear-regression.html#cb123-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&quot;Soil moisture content&quot;</span>,</span>
<span id="cb123-5"><a href="simple-linear-regression.html#cb123-5" tabindex="-1"></a>       <span class="at">y=</span><span class="st">&quot;Plant growth rate (mm/week)&quot;</span>) <span class="sc">+</span></span>
<span id="cb123-6"><a href="simple-linear-regression.html#cb123-6" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>,<span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb123-7"><a href="simple-linear-regression.html#cb123-7" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>,<span class="dv">50</span>) <span class="sc">+</span></span>
<span id="cb123-8"><a href="simple-linear-regression.html#cb123-8" tabindex="-1"></a>  <span class="fu">theme_cowplot</span>()</span></code></pre></div>
<p><img src="simple_linear_regression_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>From the plot, we note that:</p>
<ul>
<li>there is an upward trend that is plausibly linear within this range of soil misture content. The more moisture there is in the soil, the greater the growth rate of the plants appears to be.</li>
<li>the variance of the data, that is the range of vertical spread is approximately constant for the whole range of soil moisture content. This is one of the key criteria that data must satisfy if we are to analyse them using a linear model such as simple linear regression.</li>
<li>we can estimate the intercept and gradient of a best fit line just by looking at the plot. Roughly speaking, the moisture content varies from 0 to 2, while the growth rate rises from 20 to 50, a rise of about 30. Hence the gradient is about 30/2 = 15 mm/week, while the intercept is somewhere between 15 mm and 20 mm / week.</li>
</ul>
<p>It is always good practice to examine the data before you go on to do any statistical analysis.</p>
</div>
<div id="make-a-simple-model-using-linear-regression" class="section level3 hasAnchor" number="8.0.5">
<h3><span class="header-section-number">8.0.5</span> Make a simple model using linear regression<a href="simple-linear-regression.html#make-a-simple-model-using-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We use the function <code>lm()</code> to do this, and we save the results in an object to which we give the name <code>model_pgr</code>. This function needs a formula and some data as its arguments:</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="simple-linear-regression.html#cb124-1" tabindex="-1"></a>model_pgr<span class="ot">&lt;-</span><span class="fu">lm</span>(plant.growth.rate <span class="sc">~</span> soil.moisture.content, <span class="at">data =</span> plants)</span></code></pre></div>
<p>This reads: ‘Fit a linear model, where we hypothesize that plant growth rate is a function of soil moisture content, using the variables from the <code>plants</code> data frame.’</p>
</div>
<div id="check-assumptions" class="section level3 hasAnchor" number="8.0.6">
<h3><span class="header-section-number">8.0.6</span> Check assumptions<a href="simple-linear-regression.html#check-assumptions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Before we rush into interpreting the output of the model, we need to check whether it was valid to use a linear model in the first place. Whatever the test within which we are using a linear model, we should do the necessary diagnostic checks at this stage.</p>
<p>You can do this using tests designed for the purpose, but I prefer to do it graphically, using a function <code>autoplot()</code> from the package <code>ggfortify</code>. You give this the model we have just created using <code>lm()</code> and it produces four very useful graphs. I suggest that, after once installing <code>ggfortify</code> you include the line <code>library(ggfortify)</code> at the start of every script.</p>
<p>Here is how you use it:</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="simple-linear-regression.html#cb125-1" tabindex="-1"></a><span class="fu">autoplot</span>(model_pgr, <span class="at">smooth.colour=</span><span class="cn">NA</span>) <span class="sc">+</span> <span class="fu">theme_cowplot</span>()</span></code></pre></div>
<p><img src="simple_linear_regression_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>The <code>theme_cowplot()</code> part is not necessary, but it gives the plots a nice look, so why not?</p>
<p>These plots are all based around the `residuals’, which is the vertical distance between observed values and fitted values ie between each point and the best fit line through the points - the line which the linear model is finding for us, by telling us its intercept and gradient.</p>
<p>Note that in simple linear regression, the best fit line is the one that minimises that sum of the squared residuals.</p>
<p>So what do these plots mean?</p>
<ul>
<li><em>Top-left</em>: This tells you about the structure of the model. Was it a good idea to try to fit a straight line to the data? If not, for example because the data did follow a linear trend, then there will be humps or troughs in this plot.</li>
<li><em>Top-right</em>: This evaluates the assumption of normality of the residuals. The dots are the residuals and the dashed line is the expectation under the normality assumption. This is a <em>much</em> better way to check normality than making a histogram of the residuals, especially with small samples.</li>
<li><em>Bottom-left</em>: This examines the assumption of equal variance of the residuals. A linear model assumes that the variance is constant over all predicted values of the response variables. There should be no pattern. Often, however, there is. With count data, for example, the variance typically increases with the mean.</li>
<li><em>Bottom-right</em>: This detects leverage - which means points that have undue influence on the gradient of the fitted line, and outliers. If you have outliers in your data, you need to decide what to do with them.</li>
</ul>
<p>In the case of these data, we are good to go! There is no discernible pattern in either of the left-hand plots, the qq-plot is about as straight as you ever see with real data, and there are no points exerting undue high influence.</p>
</div>
<div id="interpretation-of-the-model" class="section level3 hasAnchor" number="8.0.7">
<h3><span class="header-section-number">8.0.7</span> Interpretation of the model<a href="simple-linear-regression.html#interpretation-of-the-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Now that we have established that the data meet the criteria required for the model to be valid, we can go ahead and inspect its output. We will do this using two tools that we also use for every other general linear model we implement (t-test, ANOVA etc). These are <code>anova()</code> and <code>summary()</code></p>
<p>Let us first use <code>anova()</code>:</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="simple-linear-regression.html#cb126-1" tabindex="-1"></a><span class="fu">anova</span>(model_pgr)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: plant.growth.rate
##                       Df  Sum Sq Mean Sq F value    Pr(&gt;F)    
## soil.moisture.content  1 2521.15 2521.15  156.08 &lt; 2.2e-16 ***
## Residuals             48  775.35   16.15                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The F value here is an example of a ‘test statistic’, a number that a test calculates from the data, from which it is possible to further calulate how likely it is that you would have got the data you got if the null hypothesis were true. This particular test statistic is the ratio of the variation in the data that is explained by the explanatory variable to the leftover variance. The bigger it is, the better the job that the explanatory variable is doing at explaining the variation in the dependent variable. The p value, which here is effectively zero, is the chance you would have got an F value this big or bigger from the data in the sample if in fact there were no relationship between plant growth rate and soil moisture content. If the p value is small (and by that we usually mean less than 0.05) then we can reject the null hypothesis that there is no relationship between plant growth rate and soil moisture content.</p>
<p>Hence, in this case, we emphatically reject the null: there is clear evidence that plant growth rate is at least in part explained by soil moisture content.</p>
<p>Now we use the <code>summary()</code> function:</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="simple-linear-regression.html#cb128-1" tabindex="-1"></a><span class="fu">summary</span>(model_pgr)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = plant.growth.rate ~ soil.moisture.content, data = plants)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.9089 -3.0747  0.2261  2.6567  8.9406 
## 
## Coefficients:
##                       Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)             19.348      1.283   15.08   &lt;2e-16 ***
## soil.moisture.content   12.750      1.021   12.49   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.019 on 48 degrees of freedom
## Multiple R-squared:  0.7648, Adjusted R-squared:  0.7599 
## F-statistic: 156.1 on 1 and 48 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>This gives us estimates of the intercept (19.348) and gradient (12.750) of the best fit line through the data. The null hypothesis is that both these values are zero, and the p-value is our clue as to whether we can reject this null. Here, in both cases, we clearly can.</p>
<p>We also see the <em>Adjusted R-squared</em> value of 0.7599. This is the proportion of the variance in the dependent variable that is explained by the explanatory variable. Thus it can vary between 0 and 1. A large value like this indicates that soil moisture content is a good predictor of plant growth rate.</p>
</div>
<div id="back-to-the-figure" class="section level3 hasAnchor" number="8.0.8">
<h3><span class="header-section-number">8.0.8</span> Back to the figure<a href="simple-linear-regression.html#back-to-the-figure" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Typically, a final step in our analysis involves including the model we have fitted into the original figure, if that is possible in a straightforward way. In the case of simple linear regression, it is. It means adding a straight line with the intercept and gradient displayed by the <code>summary()</code> function. We do this by adding a line <code>geom_smooth(method = "lm")</code> to our plot code:</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="simple-linear-regression.html#cb130-1" tabindex="-1"></a>plants <span class="sc">|&gt;</span></span>
<span id="cb130-2"><a href="simple-linear-regression.html#cb130-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>soil.moisture.content, <span class="at">y=</span>plant.growth.rate)) <span class="sc">+</span></span>
<span id="cb130-3"><a href="simple-linear-regression.html#cb130-3" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb130-4"><a href="simple-linear-regression.html#cb130-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>) <span class="sc">+</span></span>
<span id="cb130-5"><a href="simple-linear-regression.html#cb130-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&quot;Soil moisture content&quot;</span>,</span>
<span id="cb130-6"><a href="simple-linear-regression.html#cb130-6" tabindex="-1"></a>       <span class="at">y=</span><span class="st">&quot;Plant growth rate (mm/week)&quot;</span>) <span class="sc">+</span></span>
<span id="cb130-7"><a href="simple-linear-regression.html#cb130-7" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>,<span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb130-8"><a href="simple-linear-regression.html#cb130-8" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>,<span class="dv">50</span>) <span class="sc">+</span></span>
<span id="cb130-9"><a href="simple-linear-regression.html#cb130-9" tabindex="-1"></a>  <span class="fu">theme_cowplot</span>()</span></code></pre></div>
<p><img src="simple_linear_regression_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>This gives both a straight line and the ‘standard error’ of that line - meaning, roughly speaking, the wiggle room within which the ‘true’ line , for the population as opposed to this sample drawn from it, probably lies.</p>
</div>
<div id="conclusion" class="section level3 hasAnchor" number="8.0.9">
<h3><span class="header-section-number">8.0.9</span> Conclusion<a href="simple-linear-regression.html#conclusion" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We have carried out a simple linear regression on continuous data. This is an example of a general linear model. We first plotted the data, then we used <code>lm()</code> to fit the model. Next we inspected the validity of the model using <code>autoplot</code>. We then inspected the model itself using first <code>anova()</code> then <code>summary()</code>. Finally we included the output of the model on the plot, in this case by adding to it a straight line with the intercept and gradient determined by the regression model.</p>
</div>
<div id="sample-script" class="section level3 hasAnchor" number="8.0.10">
<h3><span class="header-section-number">8.0.10</span> Sample script<a href="simple-linear-regression.html#sample-script" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>An example script to do linear regression might look like the following, here written as though a .R script. For this to work you will need to work within a project, with the data in a subfolder of that called “data”. Here, the data is taken to be a .csv file called <code>mydata.csv</code>, with two columns of data, one called <code>x_values</code> and the other called <code>y_values</code>. You need to change these to suit your own data.</p>
<pre><code># load packages
library(tidyverse)
library(here)
library(ggfortify)
library(cowplot)

# load data
filepath &lt;- here(&quot;data&quot;, &quot;mydatafile.csv&quot;)
mydata &lt;- read_csv(filepath)
glimpse(mydata)

# plot the data
mydata |&gt;
  ggplot(aes(x=x_values, y=y_values)) +
  geom_point() +
  labs(x = &quot;X variable&quot;,
       y = &quot;Y variable&quot;) +
  theme_cowplot()

# fit the model
mydata.model &lt;- lm (y_values ~ x_values, data = mydata)

# diagnostics
autoplot(mydata.model)

# investigate the model
anova(mydata.model)
summary(mydata.model)

# replot the data, now with the model included
mydata |&gt;
  ggplot(aes(x=x_values, y=y_values)) +
  geom_point() +
  geom_smooth(method=&quot;linear&quot;) +
  labs(x = &quot;X variable&quot;,
       y = &quot;Y variable&quot;) +
  theme_cowplot()</code></pre>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="one-way-anova.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/simple_linear_regression.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["fake-book.pdf", "fake-book.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
